name: google_maps_place_picker_mb
version: 3.1.2
homepage: https://github.com/martin-braun-net/google_maps_place_picker_mb
publish_to: https://onepub.dev/api/xpdpsdavuh/
description: A Flutter plugin which provides 'Picking Place' using Google Maps widget. (MB version)
environment: 
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'
dependencies: 
  geolocator: ^10.0.1
  google_api_headers: ^2.0.0
  google_maps_flutter: ^2.5.0
  flutter_google_maps_webservices: ^1.1.1
  http: ^1.1.0
  provider: ^6.0.5
  tuple: ^2.0.2
  uuid: ^4.0.0
  package_info_plus: ^4.1.0
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
false_secrets: 
  - /example/lib/keys.dart
  - /example/android/app/src/main/AndroidManifest.xml
  - /example/ios/Runner/AppDelegate.swift
flutter: null
